- hosts: custom
  become: yes
#  connection: "local"
  vars:
    users: [ user1, user2, user3, user3 ]
#    user_pwd: $6$PYrgF9S8BNEzi0D7$VhWQMltvv9o/vJWBmEAYPvad0s1zr4Q1aFmc8ZGGNNTuJl2RUmWzYIb5cXEg.Eyxk5N1tNZOdkAi8LwPR8339.
  
  tasks:

  - 
    name: "Create user accounts"
    user:
      name: "{{ item }}"
#      groups: ""
    with_items: "{{ users }}"

  - 
    name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"

  -
    name: Recursively check ownership of users home directory
    file:
      path: "/home/{{ item }}"
      state: directory
      recurse: yes
      owner: "{{ item }}"
      group: "{{ item }}"
    with_items: "{{ users }}"

  -
    name: Check home directory permissions for user
    file:
      path: "/home/{{ item }}"
      mode: '700'
    with_items: "{{ users }}"


#    - 
#      name: set password for user
#      user:
#        name: user1
#        state: present
#        update_password: always
#        password: "{{ user_pwd }}"
#        shell: /bin/bash
#
#  - 
#    name: "Allow admin users to sudo without a password"
#    lineinfile:
#      dest: "/etc/sudoers"
#      state: "present"
#      regexp: "^%admin"
#      line: "%admin ALL=(ALL) NOPASSWD: ALL"
